// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Matrix53",
            "url": "https://github.com/matrix53",
            "email": "1079207272@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/problems": {
            "get": {
                "description": "获取用户所能查看的题目列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "获取题目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户位于哪一页，页数从1开始",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前的(题目名称)搜索关键字，为空字符串表示没有关键字，模糊匹配",
                        "name": "keyWord",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户想按什么排序，1为按题号升序，-1为按题号降序，2为按名称升序，-2为按名称降序，3为按难度升序，-3为按难度降序",
                        "name": "sorter",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息，题目列表",
                        "schema": {
                            "$ref": "#/definitions/api.GetProblemListA"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个题目，题目需要包含答案和题面",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "创建题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateProblemQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息",
                        "schema": {
                            "$ref": "#/definitions/api.CommonA"
                        }
                    }
                }
            }
        },
        "/api/v1/problems/{id}": {
            "get": {
                "description": "下载一个题目的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "下载题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "题目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "题目ID，题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述",
                        "schema": {
                            "$ref": "#/definitions/api.GetProblemA"
                        }
                    }
                }
            },
            "put": {
                "description": "更新一个题目的信息，并自动更新题目版本",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "更新题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "题目ID，题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateProblemQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息",
                        "schema": {
                            "$ref": "#/definitions/api.CommonA"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除一个题目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "删除题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "DeleteProblemQ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.DeleteProblemQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息",
                        "schema": {
                            "$ref": "#/definitions/api.CommonA"
                        }
                    }
                }
            }
        },
        "/api/v1/problems/{id}/version": {
            "get": {
                "description": "获取一个题目的版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评测模块"
                ],
                "summary": "获取题目版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "题目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息，题目版本",
                        "schema": {
                            "$ref": "#/definitions/api.GetProblemVersionA"
                        }
                    }
                }
            }
        },
        "/api/v1/user/captcha": {
            "post": {
                "description": "根据邮箱发送验证码，并更新数据库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交模块"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "邮箱",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GetCaptchaQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息",
                        "schema": {
                            "$ref": "#/definitions/api.CommonA"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "根据用户邮箱和密码等生成token，并将token返回给用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "邮箱，密码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.LoginQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息，Token",
                        "schema": {
                            "$ref": "#/definitions/api.LoginA"
                        }
                    }
                }
            }
        },
        "/api/v1/user/organizations": {
            "get": {
                "description": "根据用户token，获取用户所属的所有组织",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交模块"
                ],
                "summary": "获取用户所属的所有组织",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息，用户所属的组织",
                        "schema": {
                            "$ref": "#/definitions/api.GetUserOrganizationA"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "description": "根据用户ID，获取用户资料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交模块"
                ],
                "summary": "获取用户资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息，用户资料",
                        "schema": {
                            "$ref": "#/definitions/api.GetProfileA"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "description": "注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "社交模块"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "用户名, 邮箱, 密码, 验证码",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "是否成功，返回信息",
                        "schema": {
                            "$ref": "#/definitions/api.CommonA"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CommonA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.CreateProblemQ": {
            "type": "object",
            "properties": {
                "creator": {
                    "type": "integer"
                },
                "difficulty": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "type": "integer"
                },
                "readable": {
                    "type": "integer"
                },
                "writable": {
                    "type": "integer"
                }
            }
        },
        "api.DeleteProblemQ": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "api.GetCaptchaQ": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "api.GetProblemA": {
            "type": "object",
            "properties": {
                "creator": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "input": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "type": "integer"
                },
                "output": {
                    "type": "string"
                },
                "readable": {
                    "type": "integer"
                },
                "writable": {
                    "type": "integer"
                }
            }
        },
        "api.GetProblemListA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "problemList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Problem"
                    }
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.GetProblemVersionA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api.GetProfileA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.GetUserOrganizationA": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "organizations": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "isAdmin": {
                                "description": "用户在该组织中是否为管理员",
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.LoginA": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.LoginQ": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.RegisterQ": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.UpdateProblemQ": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "type": "integer"
                },
                "readable": {
                    "type": "integer"
                },
                "writable": {
                    "type": "integer"
                }
            }
        },
        "database.Problem": {
            "type": "object",
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "creator": {
                    "type": "integer"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organization": {
                    "type": "integer"
                },
                "readable": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                },
                "writable": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "PhoeniX API",
	Description: "PhoeniX学习平台的后端API接口",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
