definitions:
  api.CommonA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  api.CreateProblemQ:
    properties:
      creator:
        type: integer
      difficulty:
        type: integer
      name:
        type: string
      organization:
        type: integer
      readable:
        type: integer
      writable:
        type: integer
    type: object
  api.DeleteProblemQ:
    properties:
      id:
        type: integer
    type: object
  api.GetCaptchaQ:
    properties:
      email:
        type: string
    type: object
  api.GetProblemA:
    properties:
      creator:
        type: integer
      description:
        type: string
      difficulty:
        type: integer
      id:
        type: integer
      input:
        type: string
      name:
        type: string
      organization:
        type: integer
      output:
        type: string
      readable:
        type: integer
      writable:
        type: integer
    type: object
  api.GetProblemListA:
    properties:
      message:
        type: string
      problemList:
        items:
          $ref: '#/definitions/database.Problem'
        type: array
      success:
        type: boolean
      total:
        type: integer
    type: object
  api.GetProblemVersionA:
    properties:
      message:
        type: string
      success:
        type: boolean
      version:
        type: integer
    type: object
  api.GetProfileA:
    properties:
      message:
        type: string
      name:
        type: string
      success:
        type: boolean
    type: object
  api.GetUserOrganizationA:
    properties:
      message:
        type: string
      organizations:
        items:
          properties:
            id:
              type: integer
            isAdmin:
              description: 用户在该组织中是否为管理员
              type: boolean
            name:
              type: string
          type: object
        type: array
      success:
        type: boolean
    type: object
  api.LoginA:
    properties:
      id:
        type: integer
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  api.LoginQ:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.RegisterQ:
    properties:
      captcha:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  api.UpdateProblemQ:
    properties:
      difficulty:
        type: integer
      id:
        type: integer
      name:
        type: string
      organization:
        type: integer
      readable:
        type: integer
      writable:
        type: integer
    type: object
  database.Problem:
    properties:
      created_time:
        type: string
      creator:
        type: integer
      difficulty:
        type: integer
      id:
        type: integer
      name:
        type: string
      organization:
        type: integer
      readable:
        type: integer
      version:
        type: integer
      writable:
        type: integer
    type: object
info:
  contact:
    email: 1079207272@qq.com
    name: Matrix53
    url: https://github.com/matrix53
  description: PhoeniX学习平台的后端API接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: PhoeniX API
  version: "1.0"
paths:
  /api/v1/problems:
    get:
      consumes:
      - application/json
      description: 获取用户所能查看的题目列表
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 用户位于哪一页，页数从1开始
        in: path
        name: page
        required: true
        type: integer
      - description: 当前的(题目名称)搜索关键字，为空字符串表示没有关键字，模糊匹配
        in: path
        name: keyWord
        required: true
        type: string
      - description: 用户想按什么排序，1为按题号升序，-1为按题号降序，2为按名称升序，-2为按名称降序，3为按难度升序，-3为按难度降序
        in: path
        name: sorter
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，题目列表
          schema:
            $ref: '#/definitions/api.GetProblemListA'
      summary: 获取题目列表
      tags:
      - 评测模块
    post:
      consumes:
      - multipart/form-data
      description: 创建一个题目，题目需要包含答案和题面
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.CreateProblemQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 创建题目
      tags:
      - 评测模块
  /api/v1/problems/{id}:
    delete:
      consumes:
      - application/json
      description: 删除一个题目
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: DeleteProblemQ
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.DeleteProblemQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 删除题目
      tags:
      - 评测模块
    get:
      consumes:
      - application/json
      description: 下载一个题目的信息
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 题目ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 题目ID，题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述
          schema:
            $ref: '#/definitions/api.GetProblemA'
      summary: 下载题目
      tags:
      - 评测模块
    put:
      consumes:
      - multipart/form-data
      description: 更新一个题目的信息，并自动更新题目版本
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 题目ID，题目名称，题目难度，可读权限，可写权限，组织ID，输入文件，输出文件，题目描述
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.UpdateProblemQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 更新题目
      tags:
      - 评测模块
  /api/v1/problems/{id}/version:
    get:
      consumes:
      - application/json
      description: 获取一个题目的版本
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 题目ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，题目版本
          schema:
            $ref: '#/definitions/api.GetProblemVersionA'
      summary: 获取题目版本
      tags:
      - 评测模块
  /api/v1/user/captcha:
    post:
      consumes:
      - application/json
      description: 根据邮箱发送验证码，并更新数据库
      parameters:
      - description: 邮箱
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.GetCaptchaQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 发送验证码
      tags:
      - 社交模块
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 根据用户邮箱和密码等生成token，并将token返回给用户
      parameters:
      - description: 邮箱，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，Token
          schema:
            $ref: '#/definitions/api.LoginA'
      summary: 用户登录
      tags:
      - 社交模块
  /api/v1/user/organizations:
    get:
      consumes:
      - application/json
      description: 根据用户token，获取用户所属的所有组织
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，用户所属的组织
          schema:
            $ref: '#/definitions/api.GetUserOrganizationA'
      summary: 获取用户所属的所有组织
      tags:
      - 社交模块
  /api/v1/user/profile:
    get:
      consumes:
      - application/json
      description: 根据用户ID，获取用户资料
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，用户资料
          schema:
            $ref: '#/definitions/api.GetProfileA'
      summary: 获取用户资料
      tags:
      - 社交模块
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户名, 邮箱, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 注册
      tags:
      - 社交模块
swagger: "2.0"
