definitions:
  api.CaptchaValidQ:
    properties:
      email:
        type: string
    type: object
  api.RegisterA:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  api.RegisterQ:
    properties:
      captcha:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: 1079207272@qq.com
    name: Matrix53
    url: https://github.com/matrix53
  description: PhoeniX学习平台的后端API接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: PhoeniX API
  version: "1.0"
paths:
  /api/v1/captcha:
    post:
      consumes:
      - application/json
      description: 根据邮箱发送验证吗，并更新数据库
      parameters:
      - description: 邮箱
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.CaptchaValidQ'
      produces:
      - application/json
      responses:
        "200":
          description: 用户注册账号,返回注册成功信息
          schema:
            $ref: '#/definitions/api.RegisterA'
      tags:
      - 社交模块
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户名, 邮箱, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: 用户注册账号,返回注册成功信息
          schema:
            $ref: '#/definitions/api.RegisterA'
      tags:
      - 社交模块
swagger: "2.0"
