definitions:
  api.CommonA:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  api.GetCaptchaQ:
    properties:
      email:
        type: string
    type: object
  api.GetProfileA:
    properties:
      message:
        type: string
      name:
        type: string
      success:
        type: boolean
    type: object
  api.LoginA:
    properties:
      id:
        type: integer
      message:
        type: string
      success:
        type: boolean
      token:
        type: string
    type: object
  api.LoginQ:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.RegisterQ:
    properties:
      captcha:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: 1079207272@qq.com
    name: Matrix53
    url: https://github.com/matrix53
  description: PhoeniX学习平台的后端API接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: PhoeniX API
  version: "1.0"
paths:
  /api/v1/user/captcha:
    post:
      consumes:
      - application/json
      description: 根据邮箱发送验证码，并更新数据库
      parameters:
      - description: 邮箱
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.GetCaptchaQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 发送验证码
      tags:
      - 社交模块
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 根据用户邮箱和密码等生成token，并将token返回给用户
      parameters:
      - description: 邮箱，密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.LoginQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，Token
          schema:
            $ref: '#/definitions/api.LoginA'
      summary: 用户登录
      tags:
      - 社交模块
  /api/v1/user/profile:
    get:
      consumes:
      - application/json
      description: 根据用户ID，获取用户资料
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息，用户资料
          schema:
            $ref: '#/definitions/api.GetProfileA'
      summary: 获取用户资料
      tags:
      - 社交模块
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 注册新用户
      parameters:
      - description: 用户名, 邮箱, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/api.RegisterQ'
      produces:
      - application/json
      responses:
        "200":
          description: 是否成功，返回信息
          schema:
            $ref: '#/definitions/api.CommonA'
      summary: 注册
      tags:
      - 社交模块
swagger: "2.0"
