name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: build
        run: |
          cd ${{github.workspace}}
          go env -w GO111MODULE=on
          go mod tidy -compat="1.17"
          go build .

      - name: stop
        uses: nerd4ever/ssh-action@master
        with:
          command: |
            (ps -ef | grep phoenix-server | awk '{print $2}' | xargs kill -9) || true
          host: ${{ secrets.IP }}
          user: root
          pass: ${{ secrets.PASSWORD}}

      - name: transfer
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{github.workspace}}/phoenix-server
          remote: ${{secrets.DST_FOLDER}}/phoenix-server
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          rmRemote: true
          dotfiles: true

      - name: restart
        uses: nerd4ever/ssh-action@master
        with:
          command: |
            chmod +x ${{secrets.DST_FOLDER}}/phoenix-server
            (nohup ${{secrets.DST_FOLDER}}/phoenix-server &) && exit
          host: ${{ secrets.IP }}
          user: root
          pass: ${{ secrets.PASSWORD}}
